<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Heysender.SDK</PackageId>
    <Version>0.9.1</Version>
    <Company>Heysender ApS</Company>

    <RootNamespace>HS_csharp_sdk</RootNamespace>

    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
